// Generated by https://quicktype.io

export interface Auction {
  startTime: number;
  metadata: Metadata[];
  inscriptionId: string;
  nostrAddress: string;
  output: string;
  status: "RUNNING" | "PENDING" | "FINISHED" | "CLOSED";
  decreaseAmount: number;
  id: string;
  reservePrice: number;
  currentPrice: number;
  timeBetweenEachDecrease: number;
}

export interface Metadata {
  scheduledTime: number;
  id: string;
  nostrEventId: string;
  price: number;
  signedPsbt: string;
}
